Repository ha3158987/mister_camel, pull requests merged in 2021-07, with the labels that each got.

#4 feat: add html to filter component (#3)
  src/components/RecentList/Filter.js
Labels: html

#6 feat: edit filter component html (#5)
  src/components/RecentList/Filter.js
Labels: html

#12 feat: Filter 컴포넌트 분리
  src/components/RecentList/Filter.js
  src/components/RecentList/Filter.jsx
  src/components/RecentList/FilterBtns.jsx
  src/components/RecentList/FilterPopup.jsx
Labels: html

#21 feat: 기존의 Button 컴포넌트에서 공용 Button 컴포넌트로 교체 (#19)
  src/components/RecentList/FilterBtns.jsx
  src/components/RecentList/FilterPopup.jsx
  src/pages/ProductPage.jsx
Labels: bug

#23 feat: 공용 컴포넌트 Button에 속성 props 추가 (#22)
  src/components/common/Button.jsx
Labels: html

#34 update: 랜덤상품 조회 기능 추가, product style 수정(#26)
  src/components/Product/CurrentProduct.jsx
  src/components/Product/ProductList.jsx
  src/components/common/Button.jsx
  src/pages/ProductPage.jsx
Labels: bug, style

#35 style: Filter 컴포넌트 스타일링 (#25)
  package.json
  src/components/RecentList/Filter.jsx
  src/components/RecentList/FilterBtns.jsx
  src/components/RecentList/FilterPopup.jsx
  src/components/RecentList/InputGroup.jsx
  src/components/RecentList/index.js
  src/components/common/Button.jsx
  src/pages/RecentListPage.jsx
  src/styles/colors.js
  src/utils/constants/brandName.js
  yarn.lock
Labels: style

#37 fix: Product 하위 파일 경로 수정 (#36)
  src/pages/ProductPage.jsx
Labels: bug

#40 [fix] 병합 시 filter 부분 충돌 해결(#39)
  src/components/Product/ProductList.jsx
  src/components/RecentList/Filter.jsx
  src/components/RecentList/FilterPopup.jsx
  src/pages/ProductPage.jsx
  src/pages/RecentListPage.jsx
Labels: bug

#44 feat: ProductPage 최근 클릭 상품 반영 (#43)
  src/components/Product/CurrentProduct.jsx
  src/components/Product/ProductList.jsx
  src/pages/ProductPage.jsx
Labels: feature

#45 feat: Input 버튼 onChange event 연결 (#38)
  src/components/RecentList/Filter.jsx
  src/components/product/CurrentProduct.jsx
  src/components/product/ProductList.jsx
  src/components/recentList/Filter.jsx
  src/components/recentList/FilterBtns.jsx
  src/components/recentList/FilterPopup.jsx
  src/components/recentList/InputGroup.jsx
  src/components/recentList/RecentProductList.jsx
  src/components/recentList/index.js
  src/pages/RecentListPage.jsx
Labels: js

#48 관심없음 버튼 클릭 시 로컬스토리지 저장로직 구현
  src/components/product/ProductList.jsx
  src/pages/ProductPage.jsx
Labels: feature

#50 feat: recentPage에 localStorage데이터 적용(#49)
  src/pages/RecentListPage.jsx
Labels: feature

#53 feat: 브랜드 버튼별 필터링 기능 (#51)
  src/components/recentList/Filter.jsx
  src/components/recentList/FilterBtns.jsx
  src/pages/RecentListPage.jsx
  src/utils/utilFunc.js
Labels: feature, js

#57 feate: 관심없는 상품 숨기기 기능 (#54)
  src/components/recentList/Filter.jsx
  src/pages/RecentListPage.jsx
Labels: feature, js

#59 feat: Sort 기능 구현 (#58)
  src/components/recentList/Filter.jsx
  src/components/recentList/FilterBtns.jsx
  src/pages/RecentListPage.jsx
Labels: js

#61 add: Add favicon, logo image (#60)
  public/favicon.ico
  public/index.html
  public/logo192.png
  public/logo512.png
  public/manifest.json
  src/components/AppLayout.jsx
  src/images/mr.camel_logo.png
Labels: add, style

#63 fix: 관심없는 상품 숨기기 부분 버그 수정 (#62)
  src/pages/RecentListPage.jsx
Labels: bug

#66 feat: RecentListPage 로딩 추가하기 (#64)
  src/pages/RecentListPage.jsx
Labels: feature, js

#68 [fix] localStorage 데이터 초기화 이슈 해결 (#55)
  src/components/product/ProductList.jsx
  src/pages/ProductPage.jsx
Labels: fix

#69 [fix] localStorage 중복방지관련 shallow compare문제 해결 (#52)
  src/pages/ProductPage.jsx
Labels: bug, fix

#70 refactor: RecentListPage 필터 기능 부분 리팩토링 (#67)
  src/pages/RecentListPage.jsx
Labels: refactoring

#74 [feat] 관심없는 상품 클릭시 에러메세지 출력(#71)
  src/components/common/ListItem.jsx
  src/components/recentList/RecentProductList.jsx
Labels: feature

#77 fix: 관심없는 상품 숨기기 관련 버그 수정 (#72)
  src/components/recentList/Filter.jsx
  src/components/recentList/FilterBtns.jsx
  src/components/recentList/FilterPopup.jsx
  src/components/recentList/InputGroup.jsx
  src/pages/RecentListPage.jsx
Labels: bug

#79 fix: 최근 조회 순으로 보기 부분 버그 수정 (#78)
  src/pages/RecentListPage.jsx
Labels: bug
